name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: pdv
          MYSQL_USER: root
          MYSQL_PASSWORD: s3rp3nt3
          MYSQL_ROOT_PASSWORD: root-senha
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Wait for MySQL
      run: |
        until docker exec mysql mysqladmin ping -h "127.0.0.1" --silent; do
          echo "Waiting for MySQL to be up..."
          sleep 3
        done

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install
      env:
        SPRING_APPLICATION_NAME: pdv
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/pdv?allowPublicKeyRetrieval=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: s3rp3nt3
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
        SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_SHOW_SQL: false
        SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
        SPRING_JPA_PROPERTIES_HIBERNATE_TYPE: trace
        SPRING_FLYWAY_ENABLE: true
        SPRING_FLYWAY_LOCATIONS: classpath:db/migration
        SPRING_FLYWAY_VALIDATE_ON_MIGRATE: true
        SPRING_FLYWAY_DEFAULT_SCHEMA: pdv
        LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CORE_ENV: DEBUG
        MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
