name: pipeline
on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Package
      run: mvn package
  publish:
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@V3
      - uses: actions/setup-java@V3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      
      
