name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Development Environment
        run: |
          echo "Deploying to Development Environment"
          nohup java -jar target/your-application.jar &

      - name: Wait for Development Deployment to be Ready
        run: |
          echo "Waiting for Development Deployment to be ready..."
          sleep 60

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production Environment
        run: |
          echo "Deploying to Production Environment"
          nohup java -jar target/your-application.jar &

      - name: Wait for Production Deployment to be Ready
        run: |
          echo "Waiting for Production Deployment to be ready..."
          sleep 60

  smoke-test:
    needs: [deploy-dev, deploy-prod]
    runs-on: ubuntu-latest
    steps:
      - name: Perform Smoke Test
        run: |
          echo "Performing Smoke Test..."
          sleep 30
          curl -f http://localhost:8080/actuator/health || exit 1
          echo "Smoke Test Passed!"

      - name: Additional Logs
        if: failure()
        run: |
          echo "Fetching logs for debugging..."
          cat nohup.out || echo "No logs found"
